// Copyright (c) 2026 Ankur Pandey. Licensed under the MIT License.
// SPDX-License-Identifier: MIT

export const SKILL_DICTIONARY = [
  'node',
  'node.js',
  'typescript',
  'javascript',
  'react',
  'react.js',
  'angular',
  'vue',
  'next.js',
  'nestjs',
  'express',
  'java',
  'spring',
  'spring boot',
  'kotlin',
  'python',
  'django',
  'flask',
  'fastapi',
  'go',
  'golang',
  'rust',
  'c#',
  '.net',
  'php',
  'laravel',
  'ruby',
  'rails',
  'sql',
  'postgres',
  'postgresql',
  'mysql',
  'mongodb',
  'redis',
  'kafka',
  'rabbitmq',
  'elasticsearch',
  'graphql',
  'rest',
  'grpc',
  'docker',
  'kubernetes',
  'k8s',
  'terraform',
  'aws',
  'gcp',
  'azure',
  'cicd',
  'jenkins',
  'github actions',
  'gitlab ci',
  'linux',
  'bash',
  'shell',
  'aws lambda',
  'serverless',
  'microservices',
  'micro-frontends',
  'html',
  'css',
  'sass',
  'tailwind',
  'redux',
  'webpack',
  'vite',
  'jest',
  'cypress',
  'playwright',
  'testing',
  'tdd',
  'puppeteer',
  'web scraping',
  'pandas',
  'numpy',
  'machine learning',
  'deep learning',
  'nlp',
  'pytorch',
  'tensorflow',
  'llm',
  'ai',
  'rag',
  'prompt engineering',
  'data engineering',
  'etl',
  'spark',
  'airflow',
  'dbt',
  'kafka streams',
  'oauth',
  'jwt',
  'security',
  'performance',
  'oop',
  'design patterns',
  'system design',
  'scalability',
];

export const SKILL_ALIASES: Record<string, string> = {
  node: 'node.js',
  nodejs: 'node.js',
  'react.js': 'react',
  reactjs: 'react',
  postgres: 'postgresql',
  golang: 'go',
  k8s: 'kubernetes',
  'spring boot': 'spring',
  nest: 'nestjs',
  'nest.js': 'nestjs',
};
