// Copyright (c) 2026 Ankur Pandey. Licensed under the MIT License.
// SPDX-License-Identifier: MIT

/**
 * Countries as job listings write them: the name first, then other names and short forms. Matched as whole words,
 * lowercased. Short forms that are also ordinary words or US state codes ("IN", "CA") are left out.
 */
export const COUNTRIES: readonly (readonly string[])[] = [
  ['india', 'bharat'],
  // Not "america" alone: "Latin America" and "North America" are not the US.
  ['united states', 'usa', 'u.s.', 'u.s.a.', 'united states of america'],
  ['united kingdom', 'uk', 'u.k.', 'england', 'scotland', 'wales', 'northern ireland', 'great britain', 'britain'],
  ['canada'],
  ['mexico'],
  ['brazil', 'brasil'],
  ['argentina'],
  ['chile'],
  ['colombia'],
  ['peru'],
  ['uruguay'],
  ['costa rica'],
  ['ireland'],
  ['germany', 'deutschland'],
  ['france'],
  ['netherlands', 'holland', 'the netherlands'],
  ['belgium'],
  ['luxembourg'],
  ['switzerland'],
  ['austria'],
  ['spain', 'españa'],
  ['portugal'],
  ['italy', 'italia'],
  ['poland', 'polska'],
  ['czech republic', 'czechia'],
  ['slovakia'],
  ['hungary'],
  ['romania'],
  ['bulgaria'],
  ['greece'],
  ['croatia'],
  ['serbia'],
  ['ukraine'],
  ['estonia'],
  ['latvia'],
  ['lithuania'],
  ['sweden'],
  ['norway'],
  ['denmark'],
  ['finland'],
  ['iceland'],
  ['russia'],
  ['turkey', 'türkiye'],
  ['israel'],
  ['egypt'],
  ['morocco'],
  ['nigeria'],
  ['kenya'],
  ['south africa'],
  ['united arab emirates', 'uae', 'dubai', 'abu dhabi'],
  ['saudi arabia', 'ksa'],
  ['qatar'],
  ['kuwait'],
  ['oman'],
  ['bahrain'],
  ['pakistan'],
  ['bangladesh'],
  ['sri lanka'],
  ['nepal'],
  ['singapore'],
  ['malaysia'],
  ['indonesia'],
  ['philippines'],
  ['thailand'],
  ['vietnam', 'viet nam'],
  ['china'],
  ['hong kong'],
  ['taiwan'],
  ['japan'],
  ['south korea', 'korea', 'republic of korea'],
  ['australia'],
  ['new zealand'],
  ['armenia'],
  ['azerbaijan'],
  ['kazakhstan'],
  ['uzbekistan'],
  ['cyprus'],
  ['malta'],
  ['slovenia'],
  ['bosnia and herzegovina'],
  ['north macedonia'],
  ['albania'],
  ['montenegro'],
  ['moldova'],
  ['belarus'],
  ['paraguay'],
  ['bolivia'],
  ['ecuador'],
  ['venezuela'],
  ['guatemala'],
  ['panama'],
  ['dominican republic'],
  ['jamaica'],
  ['puerto rico'],
  ['myanmar'],
  ['cambodia'],
  ['laos'],
  ['mongolia'],
  ['jordan'],
  ['lebanon'],
  ['iraq'],
  ['iran'],
  ['tunisia'],
  ['algeria'],
  ['ghana'],
  ['ethiopia'],
  ['uganda'],
  ['tanzania'],
  ['rwanda'],
  ['namibia'],
  ['botswana'],
  ['zambia'],
  ['zimbabwe'],
  ['mauritius'],
];

/** Wider areas a listing can be open to - none of them one country. */
export const REGIONS_ABROAD = /\b(europe|european union|eu|emea|apac|asia[- ]pacific|latam|latin america|north america|south america|americas|middle east|gcc|africa|nordics|dach|benelux|anywhere|worldwide|global|international)\b/i;

/** "New York, NY": a US place written the US way, with its state's two letters. */
export const US_STATE_SUFFIX = /,\s*(A[KLRZ]|C[AOT]|D[CE]|FL|GA|HI|I[ADLN]|K[SY]|LA|M[ADEINOST]|N[CDEHJMVY]|O[HKR]|PA|RI|S[CD]|T[NX]|UT|V[AT]|W[AIVY])\b/;

/** Job sites that list jobs from one country only. */
export const SITE_COUNTRY: Readonly<Record<string, string>> = {
  naukri: 'india',
  instahyre: 'india',
  foundit: 'india',
  hirist: 'india',
};

/** Indeed's country sites, by the start of their address ("in.indeed.com"). */
export const INDEED_COUNTRY: Readonly<Record<string, string>> = {
  in: 'india',
  uk: 'united kingdom',
  ca: 'canada',
  au: 'australia',
  de: 'germany',
  fr: 'france',
  sg: 'singapore',
  ae: 'united arab emirates',
  nl: 'netherlands',
  ie: 'ireland',
  nz: 'new zealand',
  za: 'south africa',
  ph: 'philippines',
  my: 'malaysia',
  br: 'brazil',
  mx: 'mexico',
  es: 'spain',
  it: 'italy',
  pl: 'poland',
  jp: 'japan',
};
